swagger-api:
  version: "1.0"

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userbook
    username: postgres
    password: postgres

  data:
    jdbc:
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: POSTGRESQL
    defer-datasource-initialization: false

  sql:
    init:
      mode: always

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:userbook
#    username: test
#    password: test

server:
  port: 8091
  servlet:
    context-path: /app
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info