DROP TABLE IF EXISTS PERSON;
CREATE TABLE IF NOT EXISTS PERSON
(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    FULL_NAME VARCHAR (255),
    TITLE VARCHAR (255),
    AGE INTEGER NOT NULL
);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE IF NOT EXISTS BOOK
(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    TITLE VARCHAR (255),
    AUTHOR VARCHAR (255),
    PAGE_COUNT INTEGER NOT NULL ,
    USER_ID BIGINT
);

DROP TABLE IF EXISTS PERSON_BOOK;
CREATE TABLE IF NOT EXISTS PERSON_BOOK
(
    PERSON_ID BIGINT,
    BOOK_ID BIGINT,
    PRIMARY KEY (PERSON_ID, BOOK_ID)
);